# Generated by Django 5.1.2 on 2025-06-05 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_products_featured'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='Driscription',
            new_name='description',
        ),
    ]
